/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CreateListingRouteImport } from './routes/create-listing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as ApiUserRouteImport } from './routes/api/user'
import { Route as ApiListingsRouteImport } from './routes/api/listings'
import { Route as ApiGamesRouteImport } from './routes/api/games'
import { Route as ApiListingsIdRouteImport } from './routes/api/listings.$id'
import { Route as ApiListingsIdViewsRouteImport } from './routes/api/listings.$id.views'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateListingRoute = CreateListingRouteImport.update({
  id: '/create-listing',
  path: '/create-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingsRoute = ApiListingsRouteImport.update({
  id: '/api/listings',
  path: '/api/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesRoute = ApiGamesRouteImport.update({
  id: '/api/games',
  path: '/api/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListingsIdRoute = ApiListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiListingsRoute,
} as any)
const ApiListingsIdViewsRoute = ApiListingsIdViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => ApiListingsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-listing': typeof CreateListingRoute
  '/games': typeof GamesRoute
  '/profile': typeof ProfileRoute
  '/api/games': typeof ApiGamesRoute
  '/api/listings': typeof ApiListingsRouteWithChildren
  '/api/user': typeof ApiUserRoute
  '/game/$id': typeof GameIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/listings/$id': typeof ApiListingsIdRouteWithChildren
  '/api/listings/$id/views': typeof ApiListingsIdViewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-listing': typeof CreateListingRoute
  '/games': typeof GamesRoute
  '/profile': typeof ProfileRoute
  '/api/games': typeof ApiGamesRoute
  '/api/listings': typeof ApiListingsRouteWithChildren
  '/api/user': typeof ApiUserRoute
  '/game/$id': typeof GameIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/listings/$id': typeof ApiListingsIdRouteWithChildren
  '/api/listings/$id/views': typeof ApiListingsIdViewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-listing': typeof CreateListingRoute
  '/games': typeof GamesRoute
  '/profile': typeof ProfileRoute
  '/api/games': typeof ApiGamesRoute
  '/api/listings': typeof ApiListingsRouteWithChildren
  '/api/user': typeof ApiUserRoute
  '/game/$id': typeof GameIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/listings/$id': typeof ApiListingsIdRouteWithChildren
  '/api/listings/$id/views': typeof ApiListingsIdViewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-listing'
    | '/games'
    | '/profile'
    | '/api/games'
    | '/api/listings'
    | '/api/user'
    | '/game/$id'
    | '/listing/$id'
    | '/api/listings/$id'
    | '/api/listings/$id/views'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-listing'
    | '/games'
    | '/profile'
    | '/api/games'
    | '/api/listings'
    | '/api/user'
    | '/game/$id'
    | '/listing/$id'
    | '/api/listings/$id'
    | '/api/listings/$id/views'
  id:
    | '__root__'
    | '/'
    | '/create-listing'
    | '/games'
    | '/profile'
    | '/api/games'
    | '/api/listings'
    | '/api/user'
    | '/game/$id'
    | '/listing/$id'
    | '/api/listings/$id'
    | '/api/listings/$id/views'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateListingRoute: typeof CreateListingRoute
  GamesRoute: typeof GamesRoute
  ProfileRoute: typeof ProfileRoute
  ApiGamesRoute: typeof ApiGamesRoute
  ApiListingsRoute: typeof ApiListingsRouteWithChildren
  ApiUserRoute: typeof ApiUserRoute
  GameIdRoute: typeof GameIdRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-listing': {
      id: '/create-listing'
      path: '/create-listing'
      fullPath: '/create-listing'
      preLoaderRoute: typeof CreateListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listings': {
      id: '/api/listings'
      path: '/api/listings'
      fullPath: '/api/listings'
      preLoaderRoute: typeof ApiListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games': {
      id: '/api/games'
      path: '/api/games'
      fullPath: '/api/games'
      preLoaderRoute: typeof ApiGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/listings/$id': {
      id: '/api/listings/$id'
      path: '/$id'
      fullPath: '/api/listings/$id'
      preLoaderRoute: typeof ApiListingsIdRouteImport
      parentRoute: typeof ApiListingsRoute
    }
    '/api/listings/$id/views': {
      id: '/api/listings/$id/views'
      path: '/views'
      fullPath: '/api/listings/$id/views'
      preLoaderRoute: typeof ApiListingsIdViewsRouteImport
      parentRoute: typeof ApiListingsIdRoute
    }
  }
}

interface ApiListingsIdRouteChildren {
  ApiListingsIdViewsRoute: typeof ApiListingsIdViewsRoute
}

const ApiListingsIdRouteChildren: ApiListingsIdRouteChildren = {
  ApiListingsIdViewsRoute: ApiListingsIdViewsRoute,
}

const ApiListingsIdRouteWithChildren = ApiListingsIdRoute._addFileChildren(
  ApiListingsIdRouteChildren,
)

interface ApiListingsRouteChildren {
  ApiListingsIdRoute: typeof ApiListingsIdRouteWithChildren
}

const ApiListingsRouteChildren: ApiListingsRouteChildren = {
  ApiListingsIdRoute: ApiListingsIdRouteWithChildren,
}

const ApiListingsRouteWithChildren = ApiListingsRoute._addFileChildren(
  ApiListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateListingRoute: CreateListingRoute,
  GamesRoute: GamesRoute,
  ProfileRoute: ProfileRoute,
  ApiGamesRoute: ApiGamesRoute,
  ApiListingsRoute: ApiListingsRouteWithChildren,
  ApiUserRoute: ApiUserRoute,
  GameIdRoute: GameIdRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
