/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as CriarComunidadeRouteImport } from './routes/criar-comunidade'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as ProfileProfileFullNameRouteImport } from './routes/profile.$profileFullName'
import { Route as ComunidadesSlugRouteImport } from './routes/comunidades.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as ApiDiscordInviteStatsRouteImport } from './routes/api/discord-invite-stats'
import { Route as ApiCommunitiesRouteImport } from './routes/api/communities'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiProfileProfileFullNameRouteImport } from './routes/api/profile.$profileFullName'
import { Route as ApiCommunitiesSlugRouteImport } from './routes/api/communities.$slug'
import { Route as ApiCategoriesSlugRouteImport } from './routes/api/categories.$slug'
import { Route as ApiUsersIdLikedCommunitiesRouteImport } from './routes/api/users.$id.liked-communities'
import { Route as ApiCommunitiesSlugViewsRouteImport } from './routes/api/communities.$slug.views'
import { Route as ApiCommunitiesSlugLikesRouteImport } from './routes/api/communities.$slug.likes'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarComunidadeRoute = CriarComunidadeRouteImport.update({
  id: '/criar-comunidade',
  path: '/criar-comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRoute,
} as any)
const ProfileProfileFullNameRoute = ProfileProfileFullNameRouteImport.update({
  id: '/profile/$profileFullName',
  path: '/profile/$profileFullName',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesSlugRoute = ComunidadesSlugRouteImport.update({
  id: '/comunidades/$slug',
  path: '/comunidades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const ApiDiscordInviteStatsRoute = ApiDiscordInviteStatsRouteImport.update({
  id: '/api/discord-invite-stats',
  path: '/api/discord-invite-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunitiesRoute = ApiCommunitiesRouteImport.update({
  id: '/api/communities',
  path: '/api/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileProfileFullNameRoute =
  ApiProfileProfileFullNameRouteImport.update({
    id: '/api/profile/$profileFullName',
    path: '/api/profile/$profileFullName',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommunitiesSlugRoute = ApiCommunitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiCommunitiesRoute,
} as any)
const ApiCategoriesSlugRoute = ApiCategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiCategoriesRoute,
} as any)
const ApiUsersIdLikedCommunitiesRoute =
  ApiUsersIdLikedCommunitiesRouteImport.update({
    id: '/api/users/$id/liked-communities',
    path: '/api/users/$id/liked-communities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommunitiesSlugViewsRoute = ApiCommunitiesSlugViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => ApiCommunitiesSlugRoute,
} as any)
const ApiCommunitiesSlugLikesRoute = ApiCommunitiesSlugLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => ApiCommunitiesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/criar-comunidade': typeof CriarComunidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/communities': typeof ApiCommunitiesRouteWithChildren
  '/api/discord-invite-stats': typeof ApiDiscordInviteStatsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/profile/$profileFullName': typeof ProfileProfileFullNameRoute
  '/categories/': typeof CategoriesIndexRoute
  '/api/categories/$slug': typeof ApiCategoriesSlugRoute
  '/api/communities/$slug': typeof ApiCommunitiesSlugRouteWithChildren
  '/api/profile/$profileFullName': typeof ApiProfileProfileFullNameRoute
  '/api/communities/$slug/likes': typeof ApiCommunitiesSlugLikesRoute
  '/api/communities/$slug/views': typeof ApiCommunitiesSlugViewsRoute
  '/api/users/$id/liked-communities': typeof ApiUsersIdLikedCommunitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-comunidade': typeof CriarComunidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/communities': typeof ApiCommunitiesRouteWithChildren
  '/api/discord-invite-stats': typeof ApiDiscordInviteStatsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/profile/$profileFullName': typeof ProfileProfileFullNameRoute
  '/categories': typeof CategoriesIndexRoute
  '/api/categories/$slug': typeof ApiCategoriesSlugRoute
  '/api/communities/$slug': typeof ApiCommunitiesSlugRouteWithChildren
  '/api/profile/$profileFullName': typeof ApiProfileProfileFullNameRoute
  '/api/communities/$slug/likes': typeof ApiCommunitiesSlugLikesRoute
  '/api/communities/$slug/views': typeof ApiCommunitiesSlugViewsRoute
  '/api/users/$id/liked-communities': typeof ApiUsersIdLikedCommunitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/criar-comunidade': typeof CriarComunidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/communities': typeof ApiCommunitiesRouteWithChildren
  '/api/discord-invite-stats': typeof ApiDiscordInviteStatsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/profile/$profileFullName': typeof ProfileProfileFullNameRoute
  '/categories/': typeof CategoriesIndexRoute
  '/api/categories/$slug': typeof ApiCategoriesSlugRoute
  '/api/communities/$slug': typeof ApiCommunitiesSlugRouteWithChildren
  '/api/profile/$profileFullName': typeof ApiProfileProfileFullNameRoute
  '/api/communities/$slug/likes': typeof ApiCommunitiesSlugLikesRoute
  '/api/communities/$slug/views': typeof ApiCommunitiesSlugViewsRoute
  '/api/users/$id/liked-communities': typeof ApiUsersIdLikedCommunitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/criar-comunidade'
    | '/privacidade'
    | '/termos-de-uso'
    | '/api/categories'
    | '/api/communities'
    | '/api/discord-invite-stats'
    | '/categories/$slug'
    | '/comunidades/$slug'
    | '/profile/$profileFullName'
    | '/categories/'
    | '/api/categories/$slug'
    | '/api/communities/$slug'
    | '/api/profile/$profileFullName'
    | '/api/communities/$slug/likes'
    | '/api/communities/$slug/views'
    | '/api/users/$id/liked-communities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-comunidade'
    | '/privacidade'
    | '/termos-de-uso'
    | '/api/categories'
    | '/api/communities'
    | '/api/discord-invite-stats'
    | '/categories/$slug'
    | '/comunidades/$slug'
    | '/profile/$profileFullName'
    | '/categories'
    | '/api/categories/$slug'
    | '/api/communities/$slug'
    | '/api/profile/$profileFullName'
    | '/api/communities/$slug/likes'
    | '/api/communities/$slug/views'
    | '/api/users/$id/liked-communities'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/criar-comunidade'
    | '/privacidade'
    | '/termos-de-uso'
    | '/api/categories'
    | '/api/communities'
    | '/api/discord-invite-stats'
    | '/categories/$slug'
    | '/comunidades/$slug'
    | '/profile/$profileFullName'
    | '/categories/'
    | '/api/categories/$slug'
    | '/api/communities/$slug'
    | '/api/profile/$profileFullName'
    | '/api/communities/$slug/likes'
    | '/api/communities/$slug/views'
    | '/api/users/$id/liked-communities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  CriarComunidadeRoute: typeof CriarComunidadeRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ApiCategoriesRoute: typeof ApiCategoriesRouteWithChildren
  ApiCommunitiesRoute: typeof ApiCommunitiesRouteWithChildren
  ApiDiscordInviteStatsRoute: typeof ApiDiscordInviteStatsRoute
  ComunidadesSlugRoute: typeof ComunidadesSlugRoute
  ProfileProfileFullNameRoute: typeof ProfileProfileFullNameRoute
  ApiProfileProfileFullNameRoute: typeof ApiProfileProfileFullNameRoute
  ApiUsersIdLikedCommunitiesRoute: typeof ApiUsersIdLikedCommunitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-comunidade': {
      id: '/criar-comunidade'
      path: '/criar-comunidade'
      fullPath: '/criar-comunidade'
      preLoaderRoute: typeof CriarComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/profile/$profileFullName': {
      id: '/profile/$profileFullName'
      path: '/profile/$profileFullName'
      fullPath: '/profile/$profileFullName'
      preLoaderRoute: typeof ProfileProfileFullNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades/$slug': {
      id: '/comunidades/$slug'
      path: '/comunidades/$slug'
      fullPath: '/comunidades/$slug'
      preLoaderRoute: typeof ComunidadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/api/discord-invite-stats': {
      id: '/api/discord-invite-stats'
      path: '/api/discord-invite-stats'
      fullPath: '/api/discord-invite-stats'
      preLoaderRoute: typeof ApiDiscordInviteStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communities': {
      id: '/api/communities'
      path: '/api/communities'
      fullPath: '/api/communities'
      preLoaderRoute: typeof ApiCommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/$profileFullName': {
      id: '/api/profile/$profileFullName'
      path: '/api/profile/$profileFullName'
      fullPath: '/api/profile/$profileFullName'
      preLoaderRoute: typeof ApiProfileProfileFullNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communities/$slug': {
      id: '/api/communities/$slug'
      path: '/$slug'
      fullPath: '/api/communities/$slug'
      preLoaderRoute: typeof ApiCommunitiesSlugRouteImport
      parentRoute: typeof ApiCommunitiesRoute
    }
    '/api/categories/$slug': {
      id: '/api/categories/$slug'
      path: '/$slug'
      fullPath: '/api/categories/$slug'
      preLoaderRoute: typeof ApiCategoriesSlugRouteImport
      parentRoute: typeof ApiCategoriesRoute
    }
    '/api/users/$id/liked-communities': {
      id: '/api/users/$id/liked-communities'
      path: '/api/users/$id/liked-communities'
      fullPath: '/api/users/$id/liked-communities'
      preLoaderRoute: typeof ApiUsersIdLikedCommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communities/$slug/views': {
      id: '/api/communities/$slug/views'
      path: '/views'
      fullPath: '/api/communities/$slug/views'
      preLoaderRoute: typeof ApiCommunitiesSlugViewsRouteImport
      parentRoute: typeof ApiCommunitiesSlugRoute
    }
    '/api/communities/$slug/likes': {
      id: '/api/communities/$slug/likes'
      path: '/likes'
      fullPath: '/api/communities/$slug/likes'
      preLoaderRoute: typeof ApiCommunitiesSlugLikesRouteImport
      parentRoute: typeof ApiCommunitiesSlugRoute
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface ApiCategoriesRouteChildren {
  ApiCategoriesSlugRoute: typeof ApiCategoriesSlugRoute
}

const ApiCategoriesRouteChildren: ApiCategoriesRouteChildren = {
  ApiCategoriesSlugRoute: ApiCategoriesSlugRoute,
}

const ApiCategoriesRouteWithChildren = ApiCategoriesRoute._addFileChildren(
  ApiCategoriesRouteChildren,
)

interface ApiCommunitiesSlugRouteChildren {
  ApiCommunitiesSlugLikesRoute: typeof ApiCommunitiesSlugLikesRoute
  ApiCommunitiesSlugViewsRoute: typeof ApiCommunitiesSlugViewsRoute
}

const ApiCommunitiesSlugRouteChildren: ApiCommunitiesSlugRouteChildren = {
  ApiCommunitiesSlugLikesRoute: ApiCommunitiesSlugLikesRoute,
  ApiCommunitiesSlugViewsRoute: ApiCommunitiesSlugViewsRoute,
}

const ApiCommunitiesSlugRouteWithChildren =
  ApiCommunitiesSlugRoute._addFileChildren(ApiCommunitiesSlugRouteChildren)

interface ApiCommunitiesRouteChildren {
  ApiCommunitiesSlugRoute: typeof ApiCommunitiesSlugRouteWithChildren
}

const ApiCommunitiesRouteChildren: ApiCommunitiesRouteChildren = {
  ApiCommunitiesSlugRoute: ApiCommunitiesSlugRouteWithChildren,
}

const ApiCommunitiesRouteWithChildren = ApiCommunitiesRoute._addFileChildren(
  ApiCommunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  CriarComunidadeRoute: CriarComunidadeRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ApiCategoriesRoute: ApiCategoriesRouteWithChildren,
  ApiCommunitiesRoute: ApiCommunitiesRouteWithChildren,
  ApiDiscordInviteStatsRoute: ApiDiscordInviteStatsRoute,
  ComunidadesSlugRoute: ComunidadesSlugRoute,
  ProfileProfileFullNameRoute: ProfileProfileFullNameRoute,
  ApiProfileProfileFullNameRoute: ApiProfileProfileFullNameRoute,
  ApiUsersIdLikedCommunitiesRoute: ApiUsersIdLikedCommunitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
