/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CriarComunidadeRouteImport } from './routes/criar-comunidade'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as PerfilUsernameRouteImport } from './routes/perfil.$username'
import { Route as ComunidadesSlugRouteImport } from './routes/comunidades.$slug'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'
import { Route as ApiCommunitiesRouteImport } from './routes/api/communities'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiProfileUsernameRouteImport } from './routes/api/profile.$username'
import { Route as ApiProfileByIdIdRouteImport } from './routes/api/profile-by-id.$id'
import { Route as ApiCommunitiesSlugRouteImport } from './routes/api/communities.$slug'
import { Route as ApiCategoriesSlugRouteImport } from './routes/api/categories.$slug'
import { Route as ApiUsersIdLikedCommunitiesRouteImport } from './routes/api/users.$id.liked-communities'
import { Route as ApiCommunityLinksIdClicksRouteImport } from './routes/api/community-links.$id.clicks'
import { Route as ApiCommunitiesSlugViewsRouteImport } from './routes/api/communities.$slug.views'
import { Route as ApiCommunitiesSlugLikesRouteImport } from './routes/api/communities.$slug.likes'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarComunidadeRoute = CriarComunidadeRouteImport.update({
  id: '/criar-comunidade',
  path: '/criar-comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriasRoute,
} as any)
const PerfilUsernameRoute = PerfilUsernameRouteImport.update({
  id: '/perfil/$username',
  path: '/perfil/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesSlugRoute = ComunidadesSlugRouteImport.update({
  id: '/comunidades/$slug',
  path: '/comunidades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriasRoute,
} as any)
const ApiCommunitiesRoute = ApiCommunitiesRouteImport.update({
  id: '/api/communities',
  path: '/api/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileUsernameRoute = ApiProfileUsernameRouteImport.update({
  id: '/api/profile/$username',
  path: '/api/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileByIdIdRoute = ApiProfileByIdIdRouteImport.update({
  id: '/api/profile-by-id/$id',
  path: '/api/profile-by-id/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunitiesSlugRoute = ApiCommunitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiCommunitiesRoute,
} as any)
const ApiCategoriesSlugRoute = ApiCategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiCategoriesRoute,
} as any)
const ApiUsersIdLikedCommunitiesRoute =
  ApiUsersIdLikedCommunitiesRouteImport.update({
    id: '/api/users/$id/liked-communities',
    path: '/api/users/$id/liked-communities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommunityLinksIdClicksRoute =
  ApiCommunityLinksIdClicksRouteImport.update({
    id: '/api/community-links/$id/clicks',
    path: '/api/community-links/$id/clicks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommunitiesSlugViewsRoute = ApiCommunitiesSlugViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => ApiCommunitiesSlugRoute,
} as any)
const ApiCommunitiesSlugLikesRoute = ApiCommunitiesSlugLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => ApiCommunitiesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/criar-comunidade': typeof CriarComunidadeRoute
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/communities': typeof ApiCommunitiesRouteWithChildren
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/api/categories/$slug': typeof ApiCategoriesSlugRoute
  '/api/communities/$slug': typeof ApiCommunitiesSlugRouteWithChildren
  '/api/profile-by-id/$id': typeof ApiProfileByIdIdRoute
  '/api/profile/$username': typeof ApiProfileUsernameRoute
  '/api/communities/$slug/likes': typeof ApiCommunitiesSlugLikesRoute
  '/api/communities/$slug/views': typeof ApiCommunitiesSlugViewsRoute
  '/api/community-links/$id/clicks': typeof ApiCommunityLinksIdClicksRoute
  '/api/users/$id/liked-communities': typeof ApiUsersIdLikedCommunitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-comunidade': typeof CriarComunidadeRoute
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/communities': typeof ApiCommunitiesRouteWithChildren
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/categorias': typeof CategoriasIndexRoute
  '/api/categories/$slug': typeof ApiCategoriesSlugRoute
  '/api/communities/$slug': typeof ApiCommunitiesSlugRouteWithChildren
  '/api/profile-by-id/$id': typeof ApiProfileByIdIdRoute
  '/api/profile/$username': typeof ApiProfileUsernameRoute
  '/api/communities/$slug/likes': typeof ApiCommunitiesSlugLikesRoute
  '/api/communities/$slug/views': typeof ApiCommunitiesSlugViewsRoute
  '/api/community-links/$id/clicks': typeof ApiCommunityLinksIdClicksRoute
  '/api/users/$id/liked-communities': typeof ApiUsersIdLikedCommunitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/criar-comunidade': typeof CriarComunidadeRoute
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/communities': typeof ApiCommunitiesRouteWithChildren
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/api/categories/$slug': typeof ApiCategoriesSlugRoute
  '/api/communities/$slug': typeof ApiCommunitiesSlugRouteWithChildren
  '/api/profile-by-id/$id': typeof ApiProfileByIdIdRoute
  '/api/profile/$username': typeof ApiProfileUsernameRoute
  '/api/communities/$slug/likes': typeof ApiCommunitiesSlugLikesRoute
  '/api/communities/$slug/views': typeof ApiCommunitiesSlugViewsRoute
  '/api/community-links/$id/clicks': typeof ApiCommunityLinksIdClicksRoute
  '/api/users/$id/liked-communities': typeof ApiUsersIdLikedCommunitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/criar-comunidade'
    | '/entrar'
    | '/privacidade'
    | '/termos-de-uso'
    | '/api/categories'
    | '/api/communities'
    | '/categorias/$slug'
    | '/comunidades/$slug'
    | '/perfil/$username'
    | '/categorias/'
    | '/api/categories/$slug'
    | '/api/communities/$slug'
    | '/api/profile-by-id/$id'
    | '/api/profile/$username'
    | '/api/communities/$slug/likes'
    | '/api/communities/$slug/views'
    | '/api/community-links/$id/clicks'
    | '/api/users/$id/liked-communities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-comunidade'
    | '/entrar'
    | '/privacidade'
    | '/termos-de-uso'
    | '/api/categories'
    | '/api/communities'
    | '/categorias/$slug'
    | '/comunidades/$slug'
    | '/perfil/$username'
    | '/categorias'
    | '/api/categories/$slug'
    | '/api/communities/$slug'
    | '/api/profile-by-id/$id'
    | '/api/profile/$username'
    | '/api/communities/$slug/likes'
    | '/api/communities/$slug/views'
    | '/api/community-links/$id/clicks'
    | '/api/users/$id/liked-communities'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/criar-comunidade'
    | '/entrar'
    | '/privacidade'
    | '/termos-de-uso'
    | '/api/categories'
    | '/api/communities'
    | '/categorias/$slug'
    | '/comunidades/$slug'
    | '/perfil/$username'
    | '/categorias/'
    | '/api/categories/$slug'
    | '/api/communities/$slug'
    | '/api/profile-by-id/$id'
    | '/api/profile/$username'
    | '/api/communities/$slug/likes'
    | '/api/communities/$slug/views'
    | '/api/community-links/$id/clicks'
    | '/api/users/$id/liked-communities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  CriarComunidadeRoute: typeof CriarComunidadeRoute
  EntrarRoute: typeof EntrarRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ApiCategoriesRoute: typeof ApiCategoriesRouteWithChildren
  ApiCommunitiesRoute: typeof ApiCommunitiesRouteWithChildren
  ComunidadesSlugRoute: typeof ComunidadesSlugRoute
  PerfilUsernameRoute: typeof PerfilUsernameRoute
  ApiProfileByIdIdRoute: typeof ApiProfileByIdIdRoute
  ApiProfileUsernameRoute: typeof ApiProfileUsernameRoute
  ApiCommunityLinksIdClicksRoute: typeof ApiCommunityLinksIdClicksRoute
  ApiUsersIdLikedCommunitiesRoute: typeof ApiUsersIdLikedCommunitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-comunidade': {
      id: '/criar-comunidade'
      path: '/criar-comunidade'
      fullPath: '/criar-comunidade'
      preLoaderRoute: typeof CriarComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/perfil/$username': {
      id: '/perfil/$username'
      path: '/perfil/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof PerfilUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades/$slug': {
      id: '/comunidades/$slug'
      path: '/comunidades/$slug'
      fullPath: '/comunidades/$slug'
      preLoaderRoute: typeof ComunidadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/api/communities': {
      id: '/api/communities'
      path: '/api/communities'
      fullPath: '/api/communities'
      preLoaderRoute: typeof ApiCommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/$username': {
      id: '/api/profile/$username'
      path: '/api/profile/$username'
      fullPath: '/api/profile/$username'
      preLoaderRoute: typeof ApiProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-by-id/$id': {
      id: '/api/profile-by-id/$id'
      path: '/api/profile-by-id/$id'
      fullPath: '/api/profile-by-id/$id'
      preLoaderRoute: typeof ApiProfileByIdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communities/$slug': {
      id: '/api/communities/$slug'
      path: '/$slug'
      fullPath: '/api/communities/$slug'
      preLoaderRoute: typeof ApiCommunitiesSlugRouteImport
      parentRoute: typeof ApiCommunitiesRoute
    }
    '/api/categories/$slug': {
      id: '/api/categories/$slug'
      path: '/$slug'
      fullPath: '/api/categories/$slug'
      preLoaderRoute: typeof ApiCategoriesSlugRouteImport
      parentRoute: typeof ApiCategoriesRoute
    }
    '/api/users/$id/liked-communities': {
      id: '/api/users/$id/liked-communities'
      path: '/api/users/$id/liked-communities'
      fullPath: '/api/users/$id/liked-communities'
      preLoaderRoute: typeof ApiUsersIdLikedCommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community-links/$id/clicks': {
      id: '/api/community-links/$id/clicks'
      path: '/api/community-links/$id/clicks'
      fullPath: '/api/community-links/$id/clicks'
      preLoaderRoute: typeof ApiCommunityLinksIdClicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/communities/$slug/views': {
      id: '/api/communities/$slug/views'
      path: '/views'
      fullPath: '/api/communities/$slug/views'
      preLoaderRoute: typeof ApiCommunitiesSlugViewsRouteImport
      parentRoute: typeof ApiCommunitiesSlugRoute
    }
    '/api/communities/$slug/likes': {
      id: '/api/communities/$slug/likes'
      path: '/likes'
      fullPath: '/api/communities/$slug/likes'
      preLoaderRoute: typeof ApiCommunitiesSlugLikesRouteImport
      parentRoute: typeof ApiCommunitiesSlugRoute
    }
  }
}

interface CategoriasRouteChildren {
  CategoriasSlugRoute: typeof CategoriasSlugRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasSlugRoute: CategoriasSlugRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

interface ApiCategoriesRouteChildren {
  ApiCategoriesSlugRoute: typeof ApiCategoriesSlugRoute
}

const ApiCategoriesRouteChildren: ApiCategoriesRouteChildren = {
  ApiCategoriesSlugRoute: ApiCategoriesSlugRoute,
}

const ApiCategoriesRouteWithChildren = ApiCategoriesRoute._addFileChildren(
  ApiCategoriesRouteChildren,
)

interface ApiCommunitiesSlugRouteChildren {
  ApiCommunitiesSlugLikesRoute: typeof ApiCommunitiesSlugLikesRoute
  ApiCommunitiesSlugViewsRoute: typeof ApiCommunitiesSlugViewsRoute
}

const ApiCommunitiesSlugRouteChildren: ApiCommunitiesSlugRouteChildren = {
  ApiCommunitiesSlugLikesRoute: ApiCommunitiesSlugLikesRoute,
  ApiCommunitiesSlugViewsRoute: ApiCommunitiesSlugViewsRoute,
}

const ApiCommunitiesSlugRouteWithChildren =
  ApiCommunitiesSlugRoute._addFileChildren(ApiCommunitiesSlugRouteChildren)

interface ApiCommunitiesRouteChildren {
  ApiCommunitiesSlugRoute: typeof ApiCommunitiesSlugRouteWithChildren
}

const ApiCommunitiesRouteChildren: ApiCommunitiesRouteChildren = {
  ApiCommunitiesSlugRoute: ApiCommunitiesSlugRouteWithChildren,
}

const ApiCommunitiesRouteWithChildren = ApiCommunitiesRoute._addFileChildren(
  ApiCommunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  CriarComunidadeRoute: CriarComunidadeRoute,
  EntrarRoute: EntrarRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ApiCategoriesRoute: ApiCategoriesRouteWithChildren,
  ApiCommunitiesRoute: ApiCommunitiesRouteWithChildren,
  ComunidadesSlugRoute: ComunidadesSlugRoute,
  PerfilUsernameRoute: PerfilUsernameRoute,
  ApiProfileByIdIdRoute: ApiProfileByIdIdRoute,
  ApiProfileUsernameRoute: ApiProfileUsernameRoute,
  ApiCommunityLinksIdClicksRoute: ApiCommunityLinksIdClicksRoute,
  ApiUsersIdLikedCommunitiesRoute: ApiUsersIdLikedCommunitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
